### ISSUE TITLE
Missing option to reset status after entering wrong MFA code

### ISSUE THREAD

**Issue by wlk** [lonelyplanet/aws-mfa#20]
I have entered an incorrect 6 digit code and got following exception:

```
$aws-mfa
Enter the 6-digit code from your MFA device:
___MY_6_DIGIT_CODE___

A client error (AccessDenied) occurred when calling the GetSessionToken operation: MultiFactorAuthentication failed with invalid MFA one time pass code. 
/home/w/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
    from /home/w/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `new'
    from /home/w/.rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
    from /home/w/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-mfa-0.3.0/lib/aws_mfa.rb:97:in `load_credentials'
    from /home/w/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-mfa-0.3.0/lib/aws_mfa.rb:162:in `execute'
    from /home/w/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-mfa-0.3.0/bin/aws-mfa:7:in `<top (required)>'
    from /home/w/.rbenv/versions/2.3.0/bin/aws-mfa:23:in `load'
    from /home/w/.rbenv/versions/2.3.0/bin/aws-mfa:23:in `<main>'
```

after that I couldn't find any way to reset status, so I could retry.

Solution that worked for me was to manually remove file `~/.aws/mfa_credentials` which was empty and retry

**Comment by leejones** [comment]
Yeah, I've run into that a bunch of times. #21 should prevent this issue going forward.
